// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateSecret(ctx context.Context, arg CreateSecretParams) (Secret, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteSecret(ctx context.Context, id int64) error
	GetSecret(ctx context.Context, id int64) (Secret, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListSecrets(ctx context.Context, arg ListSecretsParams) ([]Secret, error)
	UpdateSecret(ctx context.Context, arg UpdateSecretParams) (Secret, error)
}

var _ Querier = (*Queries)(nil)
