{{- $secret := .Values.dynamicSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range $key, $value := $secret.data }}
  {{ $key | quote }}: {{ $value | b64enc | quote }}
  {{- end }}
